version: "3.9"

services:
  rstudio-targets-workflow-svalbard:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: rstudio-targets-workflow-svalbard
    environment:
      - DISABLE_AUTH=true
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio

# run `docker compose up` to start the container
# use ctrl+c or `docker compose down` to stop the container
# run `docker compose up --build` to rebuild the container
# open browser to http://localhost:8787